### ISSUE TITLE
"! LaTeX Error: Option clash for package ulem" when compiling some templates

### ISSUE THREAD

**Issue by TcheL** [HolgerGerhardt/TeXTemplates#3]
When I tried to compile the source file [Template_Dissertation.tex](https://github.com/HolgerGerhardt/TeXTemplates/blob/master/Template_Dissertation.tex) with the command `pdflatex Template_Dissertation.tex` on Ubuntu 16.04, the compiler reported the problem:
```shell
! LaTeX Error: Option clash for package ulem.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              
                                                  
l.317 \ifthenelse
                 {
?
```
and after I keyed `H <return>`, the immediate help that the compiler gave is:
```shell
The package ulem has already been loaded with options:
  [normalem]
There has now been an attempt to load it with options
  [normalem,normalbf]
Adding the global options:
  normalem,normalem,normalbf
to your \documentclass declaration may fix this.
```

To find out the usage of the package `ulem`, I searched the whole directory:
```shell
grep ulem * -r -n
0_0_Preamble/Preamble_Fonts_Charter_FiraSans.tex:134:\usepackage[normalem]{ulem}	% Do NOT change \emph to \uline!
0_0_Preamble/Preamble_Fundamental_packages.tex:200:\usepackage[normalem]{ulem}  % Do NOT change \emph to \uline!!!
```
and after I replaced `\usepackage[normalem]{ulem}` with `\usepackage[normalem, normalbf]{ulem}` at [line 134 of 0_0_Preamble/Preamble_Fonts_Charter_FiraSans.tex](https://github.com/HolgerGerhardt/TeXTemplates/blob/affbe31f0db38fd645bbd156578a1894751ce730/0_0_Preamble/Preamble_Fonts_Charter_FiraSans.tex#L134) and at [line 200 of 0_0_Preamble/Preamble_Fundamental_packages.tex](https://github.com/HolgerGerhardt/TeXTemplates/blob/affbe31f0db38fd645bbd156578a1894751ce730/0_0_Preamble/Preamble_Fundamental_packages.tex#L200), the problem was solved and the compilation was perfectly finished.

Besides, I searched the whole directory for `0_0_Preamble/Preamble_Fonts_Charter_FiraSans` and `0_0_Preamble/Preamble_Fundamental_packages`:
```shell
$ grep 0_0_Preamble/Preamble_Fonts_Charter_FiraSans *.tex -n
Template_Dissertation.tex:50:\input{0_0_Preamble/Preamble_Fonts_Charter_FiraSans}
Template_Paper.tex:34:\input{0_0_Preamble/Preamble_Fonts_Charter_FiraSans}
Template_Poster.tex:17:\input{0_0_Preamble/Preamble_Fonts_Charter_FiraSans}

$ grep 0_0_Preamble/Preamble_Fundamental_packages *.tex -n
Template_Dissertation.tex:46:\input{0_0_Preamble/Preamble_Fundamental_packages}
Template_Paper.tex:27:\input{0_0_Preamble/Preamble_Fundamental_packages}
Template_Term_Paper_DE.tex:54:\input{0_0_Preamble/Preamble_Fundamental_packages}
Template_Term_Paper_EN.tex:52:\input{0_0_Preamble/Preamble_Fundamental_packages}
Template_Thesis_BA_MA_DE.tex:50:\input{0_0_Preamble/Preamble_Fundamental_packages}
Template_Thesis_BA_MA_EN.tex:48:\input{0_0_Preamble/Preamble_Fundamental_packages}
```
That is, the same problem exists in compilation of all of the above listed templates. When we have an attempt to compile them, we should firstly modify the source files [0_0_Preamble/Preamble_Fonts_Charter_FiraSans.tex](https://github.com/HolgerGerhardt/TeXTemplates/blob/master/0_0_Preamble/Preamble_Fonts_Charter_FiraSans.tex) and [0_0_Preamble/Preamble_Fundamental_packages.tex](https://github.com/HolgerGerhardt/TeXTemplates/blob/master/0_0_Preamble/Preamble_Fundamental_packages.tex) as I mentioned above.

**Comment by HolgerGerhardt** [comment]
Thank you, [Tche](https://github.com/TcheL), for pointing this out and for your very detailed description. This “issue” never generated an _error_ message when I compiled the LaTeX files, but I have still removed all references to the [`ulem`](https://ctan.org/pkg/ulem) package, as you suggested.
